/**
 * Leasing Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lease-service@allane.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContractOverview { 
    contractId?: number;
    customerId?: number;
    /**
     * concatenated name of the customer
     */
    customerName?: string;
    vehicleId?: number;
    /**
     * concatenated name of the vehicle
     */
    vehicleName?: string;
    /**
     * vehicle identification number
     */
    vin?: string;
    monthlyRate?: number;
    vehiclePrice?: number;
}

