/**
 * Leasing Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lease-service@allane.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';


export interface CustomerPageResponse { 
    page: number;
    size: number;
    numberOfPages: number;
    numberOfItems: number;
    sort: CustomerPageResponse.SortEnum;
    overviewItems?: Array<Customer>;
}
export namespace CustomerPageResponse {
    export type SortEnum = 'UNSORTED' | 'ASC' | 'DESC';
    export const SortEnum = {
        Unsorted: 'UNSORTED' as SortEnum,
        Asc: 'ASC' as SortEnum,
        Desc: 'DESC' as SortEnum
    };
}


